AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Jon's example lambda function
      FunctionName: roma-example
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables: 
          S3_BUCKET: as-aws-lambda-zip-us-east-2-224588347132
