AWSTemplateFormatVersion: '2010-09-09'
Resources:
  foo:
    Properties:
      CodeUri: s3://as-aws-lambda-zip-us-east-2-224588347132/foo/48f2cae3a344ca1791c95cabeea68444
      Description: Jon's cheesy lambda function
      FunctionName: roma-foo
      Handler: foo.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
